// client/vue/src/app.vue
<template>
  <h1>Users</h1>
  <div v-if="loading">
    <h2>Loading, please wait...</h2>
    <button @click="abortFetchUsers">Abort</button>
  </div>
  <div v-else-if="error">
    <h2>Error</h2>
    <p>Error: {{ error.message }}</p>
    <button @click="fetchUsers">Retry</button>
  </div>
  <div v-else>
    <button @click="fetchUsers">Refresh</button>
    <table>
      <tbody>
        <tr v-for="user in users" :key="user.id">
          <td>{{ user.name }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.phone }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts" setup>
import { onMounted } from "vue";
import { useJsonPlaceholderUsers } from "@jsonplaceholder-sdk/vue";

const { users, fetchUsers, abortFetchUsers, error, loading } = useJsonPlaceholderUsers();

onMounted(fetchUsers);
</script>

// client/angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { JsonPlaceholderUsersService } from '@jsonplaceholder-sdk/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  public constructor(public readonly jsonPlaceholderUsersService: JsonPlaceholderUsersService) { }

  public ngOnInit(): void {
    this.jsonPlaceholderUsersService.fetchUsers();
  }
}

<h1>Users</h1>

<ng-container *ngIf="jsonPlaceholderUsersService.loading | async; else error">
  <p>Loading...</p>
  <button (click)="jsonPlaceholderUsersService.abortFetchUsers()">Abort</button>
</ng-container>

<ng-template #error>
  <ng-container *ngIf="jsonPlaceholderUsersService.error | async as error; else users">
    <p>Error: {{ error?.message ?? "Unknown error" }}</p>
    <button (click)="jsonPlaceholderUsersService.fetchUsers()">Retry</button>
  </ng-container>
</ng-template>

<ng-template #users>
  <button (click)="jsonPlaceholderUsersService.fetchUsers()">Refresh</button>

  <table>
    <tbody>
      <tr *ngFor="let user of jsonPlaceholderUsersService.users | async">
        <td>{{ user.name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.phone }}</td>
        <td>{{ user.website }}</td>
      </tr>
    </tbody>
  </table>
</ng-template>
